In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
hlist = pd.read_html('https://heroesofthestorm.fandom.com/wiki/Hero')

In [3]:
type(hlist)

list

In [6]:
new = hlist[7]

In [9]:
new['']

,Heroes,Heroes.1,Heroes.2,Heroes.3,Heroes.4,Heroes.5,Heroes.6,Heroes.7,Heroes.8,Heroes.9,...,Heroes.190,Heroes.191,Heroes.192,Heroes.193,Heroes.194,Heroes.195,Heroes.196,Heroes.197,Heroes.198,Heroes.199
0,Bruisers,Artanis • Chen • Deathwing • Dehaka • D.Va • G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Healers,Alexstrasza • Ana • Anduin • Auriel • Brightwi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Melee Assassins,Alarak • The Butcher • Illidan • Kerrigan • Ma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ranged Assassins,Azmodan • Cassia • Chromie • Falstad • Fenix •...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Support,Abathur • The Lost Vikings • Medivh • Zarya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Tanks,Anub'arak • Arthas • Blaze • Cho • Diablo • E....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Unknown,Mekkatorque,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
new.loc(['Heroes','Heroes.1'])

TypeError: unhashable type: 'list'

In [13]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Columns: 200 entries, Heroes to Heroes.199
dtypes: float64(198), object(2)
memory usage: 11.1+ KB

In [14]:
new

,Heroes,Heroes.1,Heroes.2,Heroes.3,Heroes.4,Heroes.5,Heroes.6,Heroes.7,Heroes.8,Heroes.9,...,Heroes.190,Heroes.191,Heroes.192,Heroes.193,Heroes.194,Heroes.195,Heroes.196,Heroes.197,Heroes.198,Heroes.199
0,Bruisers,Artanis • Chen • Deathwing • Dehaka • D.Va • G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Healers,Alexstrasza • Ana • Anduin • Auriel • Brightwi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Melee Assassins,Alarak • The Butcher • Illidan • Kerrigan • Ma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ranged Assassins,Azmodan • Cassia • Chromie • Falstad • Fenix •...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Support,Abathur • The Lost Vikings • Medivh • Zarya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Tanks,Anub'arak • Arthas • Blaze • Cho • Diablo • E....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Unknown,Mekkatorque,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
group_list = new.iloc[: 6, 0:2]

In [18]:
group_list

             Heroes                                           Heroes.1
0          Bruisers  Artanis • Chen • Deathwing • Dehaka • D.Va • G...
1           Healers  Alexstrasza • Ana • Anduin • Auriel • Brightwi...
2   Melee Assassins  Alarak • The Butcher • Illidan • Kerrigan • Ma...
3  Ranged Assassins  Azmodan • Cassia • Chromie • Falstad • Fenix •...
4           Support        Abathur • The Lost Vikings • Medivh • Zarya
5             Tanks  Anub'arak • Arthas • Blaze • Cho • Diablo • E....

In [19]:
group_list['Category'] = group_list['Heroes']

In [20]:
group_list

,Heroes,Heroes.1,Category
0,Bruisers,Artanis • Chen • Deathwing • Dehaka • D.Va • G...,Bruisers
1,Healers,Alexstrasza • Ana • Anduin • Auriel • Brightwi...,Healers
2,Melee Assassins,Alarak • The Butcher • Illidan • Kerrigan • Ma...,Melee Assassins
3,Ranged Assassins,Azmodan • Cassia • Chromie • Falstad • Fenix •...,Ranged Assassins
4,Support,Abathur • The Lost Vikings • Medivh • Zarya,Support
5,Tanks,Anub'arak • Arthas • Blaze • Cho • Diablo • E....,Tanks

In [21]:
group_list.drop(['Heroes'], axis=1)

                                            Heroes.1          Category
0  Artanis • Chen • Deathwing • Dehaka • D.Va • G...          Bruisers
1  Alexstrasza • Ana • Anduin • Auriel • Brightwi...           Healers
2  Alarak • The Butcher • Illidan • Kerrigan • Ma...   Melee Assassins
3  Azmodan • Cassia • Chromie • Falstad • Fenix •...  Ranged Assassins
4        Abathur • The Lost Vikings • Medivh • Zarya           Support
5  Anub'arak • Arthas • Blaze • Cho • Diablo • E....             Tanks

In [22]:
group_list['Heroes'] = group_list['Heroes.1']

In [25]:
group_list = group_list.drop(['Heroes.1'], axis=1)

In [26]:
group_list.to_csv(index=False)

                                              Heroes          Category
0  Artanis • Chen • Deathwing • Dehaka • D.Va • G...          Bruisers
1  Alexstrasza • Ana • Anduin • Auriel • Brightwi...           Healers
2  Alarak • The Butcher • Illidan • Kerrigan • Ma...   Melee Assassins
3  Azmodan • Cassia • Chromie • Falstad • Fenix •...  Ranged Assassins
4        Abathur • The Lost Vikings • Medivh • Zarya           Support
5  Anub'arak • Arthas • Blaze • Cho • Diablo • E....             Tanks

In [28]:
group_list.to_csv('Category.csv',index=False)