In [1]:
import pandas as pd
import numpy as np
import datetime 
import matplotlib.pyplot as plt

In [2]:
comp = pd.read_html('https://www.hotslogs.com/Sitewide/TeamCompositions?Grouping=2&Hero=-1')

In [3]:
type(comp)

list

In [4]:
comp

[    0       1
 0 NaN  Search,
      Games Played Win Percent  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
 0               6      100.0%         NaN         NaN         NaN         NaN
 1               6      100.0%         NaN         NaN         NaN         NaN
 2               5      100.0%         NaN         NaN         NaN         NaN
 3               5      100.0%         NaN         NaN         NaN         NaN
 4               5      100.0%         NaN         NaN         NaN         NaN
 ..            ...         ...         ...         ...         ...         ...
 936             5        0.0%         NaN         NaN         NaN         NaN
 937             5        0.0%         NaN         NaN         NaN         NaN
 938             5        0.0%         NaN         NaN         NaN         NaN
 939             5        0.0%         NaN         NaN         NaN         NaN
 940             5        0.0%         NaN         NaN         NaN         NaN

      Unnamed: 6
 0           NaN
 1           NaN
 2           NaN
 3           NaN
 4           NaN
 ..          ...
 936         NaN
 937         NaN
 938         NaN
 939         NaN
 940         NaN

 [941 rows x 7 columns]]

In [5]:
comp2 = pd.read_html('https://www.hotslogs.com/Sitewide/TeamCompositions?Grouping=1')

In [7]:
comp2[1]

,Games Played,Win Percent,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,9045,54.4%,NaN,NaN,NaN,NaN,NaN
1,2329,54.0%,NaN,NaN,NaN,NaN,NaN
2,2664,53.9%,NaN,NaN,NaN,NaN,NaN
3,5944,51.8%,NaN,NaN,NaN,NaN,NaN
4,3960,51.0%,NaN,NaN,NaN,NaN,NaN
5,22087,50.7%,NaN,NaN,NaN,NaN,NaN
6,26822,50.4%,NaN,NaN,NaN,NaN,NaN
7,110470,50.2%,NaN,NaN,NaN,NaN,NaN
8,1420,49.2%,NaN,NaN,NaN,NaN,NaN
9,5773,47.9%,NaN,NaN,NaN,NaN,NaN
10,1240,47.6%,NaN,NaN,NaN,NaN,NaN
11,1382,47.3%,NaN,NaN,NaN,NaN,NaN
12,3389,47.2%,NaN,NaN,NaN,NaN,NaN
13,848,46.5%,NaN,NaN,NaN,NaN,NaN
14,9140,46.2%,NaN,NaN,NaN,NaN,NaN
15,4353,46.1%,NaN,NaN,NaN,NaN,NaN
16,811,45.1%,NaN,NaN,NaN,NaN,NaN
17,3541,44.0%,NaN,NaN,NaN,NaN,NaN